title: "cat-jekyll-config-generator"
description: "cat-jekyll-config-generator"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/cat-jekyll-config-generator
