github_username = "your github username"
base_dir = "../"
theme = "jekyll-theme-slate"
description_template = "{repo_name}"

config_template = """title: "{repo_name}"
description: "{description}"
theme: {theme}
github:
  is_project_page: true
  repository_url: https://github.com/{username}/{repo_name}
"""
